//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankAppWeb.Soap.KullaniciService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanici", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Kullanici : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int kullaniciIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parolaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string kullaniciTuruField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int kullaniciId {
            get {
                return this.kullaniciIdField;
            }
            set {
                if ((this.kullaniciIdField.Equals(value) != true)) {
                    this.kullaniciIdField = value;
                    this.RaisePropertyChanged("kullaniciId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string kullaniciAd {
            get {
                return this.kullaniciAdField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciAdField, value) != true)) {
                    this.kullaniciAdField = value;
                    this.RaisePropertyChanged("kullaniciAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string parola {
            get {
                return this.parolaField;
            }
            set {
                if ((object.ReferenceEquals(this.parolaField, value) != true)) {
                    this.parolaField = value;
                    this.RaisePropertyChanged("parola");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string kullaniciTuru {
            get {
                return this.kullaniciTuruField;
            }
            set {
                if ((object.ReferenceEquals(this.kullaniciTuruField, value) != true)) {
                    this.kullaniciTuruField = value;
                    this.RaisePropertyChanged("kullaniciTuru");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KullaniciService.KullaniciWebServiceSoap")]
    public interface KullaniciWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertKullanici", ReplyAction="*")]
        BankAppWeb.Soap.KullaniciService.InsertKullaniciResponse InsertKullanici(BankAppWeb.Soap.KullaniciService.InsertKullaniciRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertKullanici", ReplyAction="*")]
        System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.InsertKullaniciResponse> InsertKullaniciAsync(BankAppWeb.Soap.KullaniciService.InsertKullaniciRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciDogrulama", ReplyAction="*")]
        BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaResponse KullaniciDogrulama(BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KullaniciDogrulama", ReplyAction="*")]
        System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaResponse> KullaniciDogrulamaAsync(BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKullanici", ReplyAction="*")]
        bool DeleteKullanici(int kullaniciId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteKullanici", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteKullaniciAsync(int kullaniciId);
        
        // CODEGEN: Generating message contract since element name SelectAllKullanicisResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllKullanicis", ReplyAction="*")]
        BankAppWeb.Soap.KullaniciService.SelectAllKullanicisResponse SelectAllKullanicis(BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectAllKullanicis", ReplyAction="*")]
        System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.SelectAllKullanicisResponse> SelectAllKullanicisAsync(BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequest request);
        
        // CODEGEN: Generating message contract since element name SelectKullaniciByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectKullaniciById", ReplyAction="*")]
        BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdResponse SelectKullaniciById(BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectKullaniciById", ReplyAction="*")]
        System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdResponse> SelectKullaniciByIdAsync(BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKullaniciRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKullanici", Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.Soap.KullaniciService.InsertKullaniciRequestBody Body;
        
        public InsertKullaniciRequest() {
        }
        
        public InsertKullaniciRequest(BankAppWeb.Soap.KullaniciService.InsertKullaniciRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKullaniciRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankAppWeb.Soap.KullaniciService.Kullanici entity;
        
        public InsertKullaniciRequestBody() {
        }
        
        public InsertKullaniciRequestBody(BankAppWeb.Soap.KullaniciService.Kullanici entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKullaniciResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKullaniciResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.Soap.KullaniciService.InsertKullaniciResponseBody Body;
        
        public InsertKullaniciResponse() {
        }
        
        public InsertKullaniciResponse(BankAppWeb.Soap.KullaniciService.InsertKullaniciResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKullaniciResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertKullaniciResult;
        
        public InsertKullaniciResponseBody() {
        }
        
        public InsertKullaniciResponseBody(bool InsertKullaniciResult) {
            this.InsertKullaniciResult = InsertKullaniciResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciDogrulamaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciDogrulama", Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequestBody Body;
        
        public KullaniciDogrulamaRequest() {
        }
        
        public KullaniciDogrulamaRequest(BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciDogrulamaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public KullaniciDogrulamaRequestBody() {
        }
        
        public KullaniciDogrulamaRequestBody(string username, string pass) {
            this.username = username;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KullaniciDogrulamaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KullaniciDogrulamaResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaResponseBody Body;
        
        public KullaniciDogrulamaResponse() {
        }
        
        public KullaniciDogrulamaResponse(BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KullaniciDogrulamaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool KullaniciDogrulamaResult;
        
        public KullaniciDogrulamaResponseBody() {
        }
        
        public KullaniciDogrulamaResponseBody(bool KullaniciDogrulamaResult) {
            this.KullaniciDogrulamaResult = KullaniciDogrulamaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllKullanicisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllKullanicis", Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequestBody Body;
        
        public SelectAllKullanicisRequest() {
        }
        
        public SelectAllKullanicisRequest(BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectAllKullanicisRequestBody {
        
        public SelectAllKullanicisRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllKullanicisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectAllKullanicisResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.Soap.KullaniciService.SelectAllKullanicisResponseBody Body;
        
        public SelectAllKullanicisResponse() {
        }
        
        public SelectAllKullanicisResponse(BankAppWeb.Soap.KullaniciService.SelectAllKullanicisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectAllKullanicisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankAppWeb.Soap.KullaniciService.Kullanici[] SelectAllKullanicisResult;
        
        public SelectAllKullanicisResponseBody() {
        }
        
        public SelectAllKullanicisResponseBody(BankAppWeb.Soap.KullaniciService.Kullanici[] SelectAllKullanicisResult) {
            this.SelectAllKullanicisResult = SelectAllKullanicisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectKullaniciByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectKullaniciById", Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequestBody Body;
        
        public SelectKullaniciByIdRequest() {
        }
        
        public SelectKullaniciByIdRequest(BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectKullaniciByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kullaniciId;
        
        public SelectKullaniciByIdRequestBody() {
        }
        
        public SelectKullaniciByIdRequestBody(int kullaniciId) {
            this.kullaniciId = kullaniciId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectKullaniciByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectKullaniciByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdResponseBody Body;
        
        public SelectKullaniciByIdResponse() {
        }
        
        public SelectKullaniciByIdResponse(BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectKullaniciByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankAppWeb.Soap.KullaniciService.Kullanici SelectKullaniciByIdResult;
        
        public SelectKullaniciByIdResponseBody() {
        }
        
        public SelectKullaniciByIdResponseBody(BankAppWeb.Soap.KullaniciService.Kullanici SelectKullaniciByIdResult) {
            this.SelectKullaniciByIdResult = SelectKullaniciByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KullaniciWebServiceSoapChannel : BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciWebServiceSoapClient : System.ServiceModel.ClientBase<BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap>, BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap {
        
        public KullaniciWebServiceSoapClient() {
        }
        
        public KullaniciWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KullaniciWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppWeb.Soap.KullaniciService.InsertKullaniciResponse BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap.InsertKullanici(BankAppWeb.Soap.KullaniciService.InsertKullaniciRequest request) {
            return base.Channel.InsertKullanici(request);
        }
        
        public bool InsertKullanici(BankAppWeb.Soap.KullaniciService.Kullanici entity) {
            BankAppWeb.Soap.KullaniciService.InsertKullaniciRequest inValue = new BankAppWeb.Soap.KullaniciService.InsertKullaniciRequest();
            inValue.Body = new BankAppWeb.Soap.KullaniciService.InsertKullaniciRequestBody();
            inValue.Body.entity = entity;
            BankAppWeb.Soap.KullaniciService.InsertKullaniciResponse retVal = ((BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap)(this)).InsertKullanici(inValue);
            return retVal.Body.InsertKullaniciResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.InsertKullaniciResponse> BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap.InsertKullaniciAsync(BankAppWeb.Soap.KullaniciService.InsertKullaniciRequest request) {
            return base.Channel.InsertKullaniciAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.InsertKullaniciResponse> InsertKullaniciAsync(BankAppWeb.Soap.KullaniciService.Kullanici entity) {
            BankAppWeb.Soap.KullaniciService.InsertKullaniciRequest inValue = new BankAppWeb.Soap.KullaniciService.InsertKullaniciRequest();
            inValue.Body = new BankAppWeb.Soap.KullaniciService.InsertKullaniciRequestBody();
            inValue.Body.entity = entity;
            return ((BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap)(this)).InsertKullaniciAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaResponse BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap.KullaniciDogrulama(BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequest request) {
            return base.Channel.KullaniciDogrulama(request);
        }
        
        public bool KullaniciDogrulama(string username, string pass) {
            BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequest inValue = new BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequest();
            inValue.Body = new BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequestBody();
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaResponse retVal = ((BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap)(this)).KullaniciDogrulama(inValue);
            return retVal.Body.KullaniciDogrulamaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaResponse> BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap.KullaniciDogrulamaAsync(BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequest request) {
            return base.Channel.KullaniciDogrulamaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaResponse> KullaniciDogrulamaAsync(string username, string pass) {
            BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequest inValue = new BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequest();
            inValue.Body = new BankAppWeb.Soap.KullaniciService.KullaniciDogrulamaRequestBody();
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            return ((BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap)(this)).KullaniciDogrulamaAsync(inValue);
        }
        
        public bool DeleteKullanici(int kullaniciId) {
            return base.Channel.DeleteKullanici(kullaniciId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteKullaniciAsync(int kullaniciId) {
            return base.Channel.DeleteKullaniciAsync(kullaniciId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppWeb.Soap.KullaniciService.SelectAllKullanicisResponse BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap.SelectAllKullanicis(BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequest request) {
            return base.Channel.SelectAllKullanicis(request);
        }
        
        public BankAppWeb.Soap.KullaniciService.Kullanici[] SelectAllKullanicis() {
            BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequest inValue = new BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequest();
            inValue.Body = new BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequestBody();
            BankAppWeb.Soap.KullaniciService.SelectAllKullanicisResponse retVal = ((BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap)(this)).SelectAllKullanicis(inValue);
            return retVal.Body.SelectAllKullanicisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.SelectAllKullanicisResponse> BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap.SelectAllKullanicisAsync(BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequest request) {
            return base.Channel.SelectAllKullanicisAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.SelectAllKullanicisResponse> SelectAllKullanicisAsync() {
            BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequest inValue = new BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequest();
            inValue.Body = new BankAppWeb.Soap.KullaniciService.SelectAllKullanicisRequestBody();
            return ((BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap)(this)).SelectAllKullanicisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdResponse BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap.SelectKullaniciById(BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequest request) {
            return base.Channel.SelectKullaniciById(request);
        }
        
        public BankAppWeb.Soap.KullaniciService.Kullanici SelectKullaniciById(int kullaniciId) {
            BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequest inValue = new BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequest();
            inValue.Body = new BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequestBody();
            inValue.Body.kullaniciId = kullaniciId;
            BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdResponse retVal = ((BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap)(this)).SelectKullaniciById(inValue);
            return retVal.Body.SelectKullaniciByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdResponse> BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap.SelectKullaniciByIdAsync(BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequest request) {
            return base.Channel.SelectKullaniciByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdResponse> SelectKullaniciByIdAsync(int kullaniciId) {
            BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequest inValue = new BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequest();
            inValue.Body = new BankAppWeb.Soap.KullaniciService.SelectKullaniciByIdRequestBody();
            inValue.Body.kullaniciId = kullaniciId;
            return ((BankAppWeb.Soap.KullaniciService.KullaniciWebServiceSoap)(this)).SelectKullaniciByIdAsync(inValue);
        }
    }
}
